#!/usr/bin/env python3
"""Build /Users/ken/Documents/Transcript/index.html from all BPR HTML files.

Scans the directory for files matching `<YYYY-MM-DD>_<source>_<...>.html`,
extracts each file's <h1>, .hero-zh, .hero-eyebrow, and renders a single-page
landing/library at index.html. Designed for bpr.ken.solar.

Usage:
  /usr/bin/python3 ~/.claude/skills/bpr-skill/scripts/build_index.py

Idempotent: just rerun whenever new BPR files land in the dir.
"""
from __future__ import annotations

import re
import sys
from datetime import date as _date
from html import escape
from pathlib import Path

TRANSCRIPT_DIR = Path("/Users/ken/Documents/Transcript")
INDEX_PATH = TRANSCRIPT_DIR / "index.html"

FILENAME_RE = re.compile(r"^(\d{4}-\d{2}-\d{2})_([^_]+)_(.+)\.html$")
TAG_STRIP_RE = re.compile(r"<[^>]+>")
WS_RE = re.compile(r"\s+")


def clean(text: str) -> str:
    text = TAG_STRIP_RE.sub("", text)
    text = WS_RE.sub(" ", text)
    return text.strip()


def extract_h1_with_em(html: str) -> str:
    """Extract <h1> content, preserving <em> tags for emphasis styling."""
    m = re.search(r"<h1[^>]*>(.+?)</h1>", html, re.DOTALL)
    if not m:
        return ""
    inner = m.group(1)
    # Keep <em>...</em> markers; strip everything else
    inner = re.sub(r"<(?!/?em\b)[^>]+>", "", inner, flags=re.IGNORECASE)
    return WS_RE.sub(" ", inner).strip()


def extract_field(html: str, css_class: str) -> str:
    pattern = (
        rf'class="[^"]*\b{re.escape(css_class)}\b[^"]*"[^>]*>(.+?)</'
        r"(?:p|div|h[1-6]|span|section|header|footer|article)>"
    )
    m = re.search(pattern, html, re.DOTALL)
    return clean(m.group(1)) if m else ""


def parse_entry(path: Path) -> dict | None:
    m = FILENAME_RE.match(path.name)
    if not m:
        return None
    iso, source, rest = m.groups()
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except Exception:
        return None
    # check for matching poster PNG (only generated by /bpr all)
    stem = path.stem  # filename without .html
    poster = TRANSCRIPT_DIR / f"{stem}-poster.png"
    poster_href = f"{stem}-poster.png" if poster.exists() else None
    return {
        "iso": iso,
        "year": iso[:4],
        "source": source,
        "rest": rest,
        "href": path.name,
        "poster_href": poster_href,
        "h1": extract_h1_with_em(text) or rest.replace("-", " ").title(),
        "zh": extract_field(text, "hero-zh"),
        "eyebrow": extract_field(text, "hero-eyebrow"),
    }


def collect_entries() -> list[dict]:
    entries: list[dict] = []
    for f in TRANSCRIPT_DIR.glob("*.html"):
        if f.name == "index.html":
            continue
        if f.name.endswith("-poster.html"):
            continue
        e = parse_entry(f)
        if e:
            entries.append(e)
    entries.sort(key=lambda x: x["iso"], reverse=True)
    return entries


def render_entry_li(e: dict) -> str:
    iso = e["iso"]
    pretty_date = f'{iso[:4]} · {iso[5:7]} · {iso[8:10]}'
    h1_html = e["h1"]
    zh = escape(e["zh"]) if e["zh"] else ""
    eyebrow = escape(e["eyebrow"]) if e["eyebrow"] else ""
    href = escape(e["href"])
    source_tag = escape(e["source"])
    has_poster = bool(e.get("poster_href"))
    poster_href = escape(e["poster_href"]) if has_poster else ""
    cls = "entry has-poster" if has_poster else "entry"

    poster_block = ""
    if has_poster:
        poster_block = f"""
  <a class="entry-poster" href="{poster_href}" target="_blank" rel="noopener" aria-label="海报 PNG">
    <img src="{poster_href}" loading="lazy" alt="">
    <span class="entry-poster-badge">📷</span>
  </a>"""

    return f"""<li class="{cls}">
  <div class="entry-date">{pretty_date}</div>
  <div class="entry-body">
    <div class="entry-source">{source_tag}</div>
    <a class="entry-h1-link" href="{href}"><h3 class="entry-h1">{h1_html}</h3></a>
    {f'<div class="entry-zh">{zh}</div>' if zh else ''}
    {f'<div class="entry-eyebrow">{eyebrow}</div>' if eyebrow else ''}
  </div>{poster_block}
</li>"""


def render_index(entries: list[dict]) -> str:
    today = _date.today().isoformat()
    by_year: dict[str, list[dict]] = {}
    for e in entries:
        by_year.setdefault(e["year"], []).append(e)
    years_sorted = sorted(by_year.keys(), reverse=True)

    sections_html = []
    for y in years_sorted:
        items = "\n".join(render_entry_li(e) for e in by_year[y])
        sections_html.append(
            f'<section class="year-block">\n'
            f'  <h2 class="year">{y}</h2>\n'
            f'  <ul class="entries">\n{items}\n  </ul>\n'
            f'</section>'
        )
    sections = "\n\n".join(sections_html)
    count = len(entries)

    return f"""<!DOCTYPE html>
<html lang="zh-CN" data-theme="light">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>BPR · Read in Both Worlds · ken.solar</title>
  <meta name="description" content="Editorial-grade bilingual reader. Three-step translation. Slow reading for the AI era.">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500&family=Noto+Serif+SC:wght@400;500;600;700&display=swap" rel="stylesheet">
  <style>
    :root {{
      --paper:#f5efe4; --ink:#2a2520; --ink-soft:#5c554c; --ink-faint:#8a8278;
      --rule:#c9bfae; --accent:#b04a2f; --accent-soft:#d68a72;
      --sun-1:#f3a93b; --sun-2:#e57341;
      --serif-en:'Playfair Display',Georgia,serif;
      --serif-zh:'Noto Serif SC',-apple-system,'PingFang SC',serif;
      --sans:Inter,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;
    }}
    [data-theme="dark"] {{
      --paper:#1a1612; --ink:#e8dfd1; --ink-soft:#b5ac9e; --ink-faint:#7a7264;
      --rule:#3a3128; --accent:#e07050; --accent-soft:#a85b3f;
      --sun-1:#e57341; --sun-2:#a85b3f;
    }}
    *{{box-sizing:border-box}}
    html,body{{margin:0;padding:0}}
    body{{
      background:var(--paper); color:var(--ink);
      font-family:var(--serif-zh); line-height:1.7;
      -webkit-font-smoothing:antialiased;
      transition:background .25s, color .25s;
    }}
    a{{color:inherit; text-decoration:none}}

    /* sun glow background */
    body::before{{
      content:''; position:fixed; top:-200px; right:-200px; width:600px; height:600px;
      background:radial-gradient(circle, rgba(243,169,59,0.18) 0%, rgba(229,115,65,0.08) 40%, transparent 70%);
      pointer-events:none; z-index:0;
    }}
    [data-theme="dark"] body::before{{
      background:radial-gradient(circle, rgba(229,115,65,0.12) 0%, rgba(168,91,63,0.06) 40%, transparent 70%);
    }}

    .theme-toggle{{
      position:fixed; top:20px; right:20px; z-index:50;
      width:40px; height:40px; border:1px solid var(--rule); border-radius:50%;
      background:var(--paper); color:var(--ink-soft);
      font-size:18px; cursor:pointer;
      display:flex; align-items:center; justify-content:center;
      transition:all .15s;
    }}
    .theme-toggle:hover{{color:var(--accent); border-color:var(--accent-soft)}}

    .container{{
      max-width:780px; margin:0 auto;
      padding:80px 28px 120px;
      position:relative; z-index:1;
    }}

    /* sun mark */
    .sun-mark{{
      width:48px; height:48px;
      margin-bottom:32px;
      display:block;
    }}

    .hero{{margin-bottom:96px}}
    .eyebrow{{
      font-family:var(--sans); font-size:12px; letter-spacing:.22em;
      text-transform:uppercase; color:var(--ink-faint);
      margin-bottom:28px;
    }}
    .hero h1{{
      font-family:var(--serif-en); font-weight:700;
      font-size:64px; line-height:1.04; margin:0 0 18px;
      letter-spacing:-.02em;
    }}
    .hero h1 em{{
      font-style:italic; color:var(--accent);
    }}
    @media(max-width:768px){{ .hero h1{{font-size:42px}} }}
    .hero-zh{{
      font-family:var(--serif-zh); font-weight:500;
      font-size:20px; color:var(--ink-soft);
      margin-bottom:36px; letter-spacing:.02em;
    }}
    .lede p{{
      font-family:var(--serif-zh); font-size:16.5px;
      color:var(--ink-soft); line-height:1.85;
      margin:0 0 14px; max-width:640px;
    }}
    .lede em{{font-family:var(--serif-en); font-style:italic; color:var(--ink); font-weight:500}}
    .tagline{{
      font-family:var(--serif-en); font-style:italic;
      font-size:18px; color:var(--accent);
      margin-top:24px;
    }}
    .meta-bar{{
      margin-top:42px; padding-top:24px;
      border-top:1px solid var(--rule);
      display:flex; gap:32px; flex-wrap:wrap;
      font-family:var(--sans); font-size:12px;
      color:var(--ink-faint); letter-spacing:.05em;
    }}
    .meta-bar strong{{color:var(--ink-soft); font-weight:500; margin-right:6px}}

    .year-block{{margin:72px 0}}
    .year{{
      font-family:var(--serif-en); font-weight:500;
      font-size:14px; letter-spacing:.4em;
      color:var(--accent); margin:0 0 36px;
      padding-bottom:16px; border-bottom:1px solid var(--rule);
    }}
    .entries{{list-style:none; margin:0; padding:0}}
    .entry{{
      margin:0;
      display:grid;
      grid-template-columns:120px 1fr;
      gap:32px;
      padding:24px 0;
      border-bottom:1px dashed var(--rule);
      align-items:start;
      transition:background .15s;
    }}
    .entry.has-poster{{
      grid-template-columns:120px 1fr 110px;
    }}
    .entry:last-child{{border-bottom:none}}
    .entry:hover{{background:rgba(176,74,47,0.04)}}
    [data-theme="dark"] .entry:hover{{background:rgba(224,112,80,0.06)}}
    @media(max-width:600px){{
      .entry, .entry.has-poster{{
        grid-template-columns:1fr; gap:12px; padding:20px 0;
      }}
    }}
    .entry-date{{
      font-family:var(--sans); font-size:12px; letter-spacing:.1em;
      color:var(--ink-faint); padding-top:6px;
    }}
    .entry-source{{
      display:inline-block;
      font-family:var(--sans); font-size:10px; font-weight:500;
      letter-spacing:.18em; text-transform:uppercase;
      color:var(--accent-soft);
      margin-bottom:8px;
    }}
    .entry-h1-link{{display:block}}
    .entry-h1{{
      font-family:var(--serif-en); font-weight:600;
      font-size:24px; line-height:1.25; margin:0 0 8px;
      transition:color .15s;
    }}
    .entry-h1 em{{font-style:italic; color:var(--accent)}}
    .entry:hover .entry-h1{{color:var(--accent)}}
    .entry-zh{{
      font-family:var(--serif-zh); font-size:14.5px;
      color:var(--ink-soft); line-height:1.6;
      margin-bottom:8px;
    }}
    .entry-eyebrow{{
      font-family:var(--sans); font-size:11px;
      color:var(--ink-faint); letter-spacing:.04em;
    }}

    /* poster thumbnail (only for entries with -poster.png) */
    .entry-poster{{
      position:relative; display:block;
      width:110px; height:150px;
      border-radius:6px; overflow:hidden;
      background:#1a1a1a;
      border:1px solid var(--rule);
      box-shadow:0 4px 14px -4px rgba(0,0,0,0.15);
      transition:transform .25s ease, box-shadow .25s ease;
      align-self:start;
    }}
    .entry-poster:hover{{
      transform:translateY(-2px) scale(1.03);
      box-shadow:0 8px 24px -6px rgba(0,0,0,0.25);
    }}
    .entry-poster img{{
      width:100%; height:100%;
      object-fit:cover; object-position:top;  /* show hero portion */
      display:block;
    }}
    .entry-poster-badge{{
      position:absolute; bottom:6px; right:6px;
      background:rgba(0,0,0,0.65); color:#fff;
      font-size:10px; padding:2px 6px;
      border-radius:4px;
      letter-spacing:.05em;
      backdrop-filter:blur(6px);
    }}
    @media(max-width:600px){{
      .entry-poster{{
        width:100%; height:200px;
      }}
      .entry-poster img{{ object-position:top center }}
    }}

    footer{{
      margin-top:120px; padding-top:36px;
      border-top:1px solid var(--rule);
      font-family:var(--sans); font-size:12px;
      color:var(--ink-faint); line-height:1.7;
      display:flex; justify-content:space-between; flex-wrap:wrap; gap:16px;
    }}
    footer a{{color:var(--ink-soft); border-bottom:1px dotted var(--rule)}}
    footer a:hover{{color:var(--accent); border-bottom-color:var(--accent)}}
  </style>
</head>
<body>

  <button class="theme-toggle" aria-label="切换主题">◐</button>

  <div class="container">

    <header class="hero">
      <svg class="sun-mark" viewBox="0 0 48 48" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
        <circle cx="24" cy="24" r="9" fill="var(--sun-1)"/>
        <g stroke="var(--accent)" stroke-width="2" stroke-linecap="round">
          <line x1="24" y1="3"  x2="24" y2="11"/>
          <line x1="24" y1="37" x2="24" y2="45"/>
          <line x1="3"  y1="24" x2="11" y2="24"/>
          <line x1="37" y1="24" x2="45" y2="24"/>
          <line x1="9"  y1="9"  x2="14.5" y2="14.5"/>
          <line x1="33.5" y1="33.5" x2="39" y2="39"/>
          <line x1="9"  y1="39" x2="14.5" y2="33.5"/>
          <line x1="33.5" y1="14.5" x2="39" y2="9"/>
        </g>
      </svg>
      <div class="eyebrow">BPR · ken.solar · 2026—</div>
      <h1>Read in <em>Both Worlds</em></h1>
      <div class="hero-zh">双语阅读日志 · Editorial-grade Bilingual Reader</div>
      <div class="lede">
        <p>把高密度的英文播客与长文,慢慢嚼成<em>可以重复读</em>的双语版本。</p>
        <p>每一篇都跑一遍 <em>Translate → Reflect → Improve</em> 三步法翻译,然后用印刷品级的字体排版,做成单文件 HTML。</p>
        <p>不为快,只为耐心读者。</p>
      </div>
      <div class="tagline">Slow reading for the AI era.</div>
      <div class="meta-bar">
        <div><strong>已收录</strong>{count} 篇</div>
        <div><strong>更新</strong>{today}</div>
        <div><strong>站点</strong><a href="https://ken.solar">ken.solar</a></div>
      </div>
    </header>

{sections}

    <footer>
      <div>by <strong style="color:var(--ink-soft)">ken</strong> · built with <code style="font-family:ui-monospace,Menlo,monospace;background:rgba(176,74,47,.08);padding:1px 6px;border-radius:4px;color:var(--accent)">/bpr</code></div>
      <div>{count} entries · last build {today}</div>
    </footer>

  </div>

  <script>
    (function(){{
      var t=document.querySelector('.theme-toggle');
      var saved=localStorage.getItem('bpr-theme');
      if(saved){{document.documentElement.dataset.theme=saved}}
      t.addEventListener('click',function(){{
        var cur=document.documentElement.dataset.theme;
        var next=cur==='dark'?'light':'dark';
        document.documentElement.dataset.theme=next;
        localStorage.setItem('bpr-theme',next);
      }});
    }})();
  </script>

</body>
</html>
"""


def main() -> int:
    entries = collect_entries()
    if not entries:
        print("No BPR entries found.", file=sys.stderr)
        return 1
    html = render_index(entries)

    # L5 hard rule: macOS FS is case-insensitive but case-preserving.
    # If a stale INDEX.html (uppercase) exists, plain write_text("index.html")
    # silently overwrites it but keeps the uppercase filename, and Vercel
    # serves only lowercase index.html as root → bpr.ken.solar 404.
    # Solve: explicitly unlink any existing match first, then write fresh.
    for cand in ("index.html", "INDEX.html", "Index.html"):
        p = TRANSCRIPT_DIR / cand
        if p.exists():
            p.unlink()
    INDEX_PATH.write_text(html, encoding="utf-8")
    print(f"✓ wrote {INDEX_PATH} ({len(html):,} chars, {len(entries)} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
